### ISSUE TITLE
user and record not taken into account

### ISSUE THREAD

**Issue by bkDJ** [EmpaticoOrg/pundit-cache#1]
https://github.com/EmpaticoOrg/pundit-cache/blob/c1319b5e787c65dccf1b498db133e8752b4a3aa4/lib/pundit/cache.rb#L12

Don't the two backslashes make this **not** work the way it's intended?

**Comment by cainlevy** [comment]
There's a bit of indirection here because of the metaprogramming. We're defining a method that should perform interpolation.

Thankfully the [tests pass](https://github.com/EmpaticoOrg/pundit-cache/blob/master/test/pundit/cache_test.rb#L49-L57) too!
